version: '3.7'

services:
  api:
    image: dnyf-users-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4103:4103
    networks:
      dnyfcomposite:
        aliases:
          - dnyf-users-microservice
      dnyfnet:
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbuser
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=dnyf_users_db
    volumes:
      - "./users.sql:/docker-entrypoint-initdb.d/01.sql"
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      dnyfcomposite:
      dnyfnet:
        aliases:
          - dnyf_users_db

volumes:
  mysql:
  mysql_config:

networks:
  dnyfnet:
  dnyfcomposite:
    external: true