version: "3.7"

services:
  dnyf_user_app:
    build: .
    container_name: dnyf_user_app
    command: python3 src/app.py
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@dnyf_user_db/fastapi

  dnyf_user_db:
    image: postgres:12.1-alpine
    container_name: dnyf_user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

volumes:
  postgres_data:
