version: '3.7'

services:
  api:
    image: dnyf-users-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4103:4103
    networks:
      dnyfcomposite:
        aliases:
          - dnyf-users-microservice
      dnyfnet:
networks:
  dnyfnet:
  dnyfcomposite:
    external: true
