# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: dnyf

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          SHA=${{github.sha}}
          TAG=${SHA:0:7}
          IMAGE_NAME=dnyf_user_api
          CONTAINER_NAME=dnyf_user_api_container
          
          docker build -t $IMAGE_NAME:$TAG .
          docker build -t $IMAGE_NAME:latest .
      - name: Deploy container
        run: |
          IMAGE_NAME=dnyf_user_api
          CONTAINER_NAME=dnyf_user_api_container
          
          docker rm -f $CONTAINER_NAME
          docker run -d \
            -p 8000:8000 \
            --name $CONTAINER_NAME \
            $IMAGE_NAME:latest
          
