# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: dnyf

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          SHA=${{github.sha}}
          TAG=${SHA:0:7}
          IMAGE_NAME=dnyf_user_api
          CONTAINER_NAME=dnyf_user_api_container
          
          docker build -t $IMAGE_NAME:$TAG .
          docker build -t $IMAGE_NAME:latest .
          
          docker rm -f $CONTAINER_NAME
          docker run -d $CONTAINER_NAME $IMAGE_NAME:latest
          
